# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39d7333749185aeb09c1327aa167ae7b235bde2d0e04876d6136f7e4b48221525489143440e84b4c556ee7895d3530f59db03b282b5e86fc0222688fe1cc291

test:
  secret_key_base: 60958dd2defd439a0cf6b2aaeb6b76104f4d4e0ed8c35dddb807fb96b6364d5167fa78d0761dd38ed4c817cfc4d46b28fdf6ea533d7fdf35b42177a7fb3db006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
